all:
	pdflatex sassy.tex
	bibtex sassy.aux
	pdflatex sassy.tex
	pdflatex sassy.tex

martin:
	pdflatex sassy.tex
	bibtex sassy.aux
	pdflatex sassy.tex
	pdflatex sassy.tex
	open sassy.pdf

clean:
	rm -rf *.blg *.log *.pdf *.bbl *.aux *~
